Vehicles = {}
Vehicles2 = {}
Categories = {}
VehiclesData = {
    {
        model = 'asbo',        -- This has to match the spawn code of the vehicle
        name = 'Asbo',         -- This is the display of the vehicle
        brand = 'Maxwell',     -- This is the vehicle's brand
        price = 4000,          -- The price that the vehicle sells for
        category = 'compacts', -- Catgegory of the vehilce, stick with GetVehicleClass() options https://docs.fivem.net/natives/?_0x29439776AAA00A62
        type = 'automobile',   -- Vehicle type, refer here https://docs.fivem.net/natives/?_0x6AE51D4B & here https://docs.fivem.net/natives/?_0xA273060E
        shop = 'pdm',          -- Can be a single shop or multiple shops. For multiple shops for example {'shopname1','shopname2','shopname3'}
    },
    { model = 'arias',         name = 'Arias',                         brand = 'Jhon',            price = 70000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'blista',        name = 'Blista',                        brand = 'Dinka',           price = 40000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'brioso',        name = 'Brioso R/A',                    brand = 'Grotti',          price = 50000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'club',          name = 'Club',                          brand = 'BF',              price = 25000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'dilettante',    name = 'Dilettante',                    brand = 'Karin',           price = 40000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'dilettante2',   name = 'Dilettante Patrol',             brand = 'Karin',           price = 45000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'kanjo',         name = 'Blista Kanjo',                  brand = 'Dinka',           price = 55000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'panto',         name = 'Panto',                         brand = 'Benefactor',      price = 50000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'prairie',       name = 'Prairie',                       brand = 'Bollokan',        price = 100000,  category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'rhapsody',      name = 'Rhapsody',                      brand = 'Declasse',        price = 35000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'brioso2',       name = 'Brioso 300',                    brand = 'Grotti',          price = 30000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'weevil',        name = 'Weevil',                        brand = 'BF',              price = 45000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'issi7',         name = 'Issi Sport',                    brand = 'Weeny',           price = 100000,  category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'blista2',       name = 'Blista Compact',                brand = 'Dinka',           price = 60000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'blista3',       name = 'Blista Go Go Monkey',           brand = 'Dinka',           price = 65000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'brioso3',       name = 'Brioso 300 Widebody',           brand = 'Grotti',          price = 35000,   category = 'compacts',       type = 'automobile', shop = 'pdm' },
    { model = 'boor',          name = 'Boor',                          brand = 'Karin',           price = 100000,  category = 'compacts',       type = 'automobile', shop = 'pdm' },
    --- Sedans
    { model = 'eu_konitofas',  name = 'Tofaş',                         brand = 'Şahin',           price = 100000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'tempra',        name = 'tempra',                        brand = 'Fiat',            price = 50000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'asea',          name = 'Asea',                          brand = 'Declasse',        price = 80000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'asterope',      name = 'Asterope',                      brand = 'Karin',           price = 90000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'cog55',         name = 'Cognoscenti 55',                brand = 'Enus',            price = 120000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'cognoscenti',   name = 'Cognoscenti',                   brand = 'Enus',            price = 225000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'emperor',       name = 'Emperor',                       brand = 'Albany',          price = 150000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'fugitive',      name = 'Fugitive',                      brand = 'Cheval',          price = 70000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'glendale',      name = 'Glendale',                      brand = 'Benefactor',      price = 80000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'glendale2',     name = 'Glendale Custom',               brand = 'Benefactor',      price = 90000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'ingot',         name = 'Ingot',                         brand = 'Vulcar',          price = 90000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'intruder',      name = 'Intruder',                      brand = 'Karin',           price = 100000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'premier',       name = 'Premier',                       brand = 'Declasse',        price = 110000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'primo',         name = 'Primo',                         brand = 'Albany',          price = 100000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'primo2',        name = 'Primo Custom',                  brand = 'Albany',          price = 110000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'regina',        name = 'Regina',                        brand = 'Dundreary',       price = 80000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'stanier',       name = 'Stanier',                       brand = 'Vapid',           price = 70000,   category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'stretch',       name = 'Stretch',                       brand = 'Dundreary',       price = 2500000, category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'superd',        name = 'Super Diamond',                 brand = 'Enus',            price = 200000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'surge',         name = 'Surge',                         brand = 'Cheval',          price = 200000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'tailgater',     name = 'Tailgater',                     brand = 'Obey',            price = 110000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'washington',    name = 'Washington',                    brand = 'Albany',          price = 300000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'tailgater2',    name = 'Tailgater S',                   brand = 'Obey',            price = 800000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'cinquemila',    name = 'Lampadati',                     brand = 'Cinquemila',      price = 300000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'oracle',        name = 'Oracle',                        brand = 'Übermacht',       price = 200000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'schafter2',     name = 'Schafter',                      brand = 'Benefactor',      price = 200000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'warrener2',     name = 'Warrener HKR',                  brand = 'Vulcar',          price = 300000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'rhinehart',     name = 'Rhinehart',                     brand = 'Übermacht',       price = 350000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    { model = 'eudora',        name = 'Eudora',                        brand = 'Willard',         price = 300000,  category = 'sedans',         type = 'automobile', shop = 'pdm' },
    --- SUV (2)
    { model = 'baller',        name = 'Baller',                        brand = 'Gallivanter',     price = 400000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'baller2',       name = 'Baller II',                     brand = 'Gallivanter',     price = 500000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'baller3',       name = 'Baller LE',                     brand = 'Gallivanter',     price = 600000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'baller4',       name = 'Baller LE LWB',                 brand = 'Gallivanter',     price = 700000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'baller5',       name = 'Baller LE (Armored)',           brand = 'Gallivanter',     price = 700000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'iwagen',        name = 'Obey',                          brand = 'I-Wagen',         price = 500000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'astron',        name = 'Astron',                        brand = 'Pfister',         price = 500000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'baller7',       name = 'Baller ST',                     brand = 'Gallivanter',     price = 800000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'baller8',       name = 'Baller ST 8',                   brand = 'Gallivanter',     price = 850000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'jubilee',       name = 'Jubilee',                       brand = 'Enus',            price = 485000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'dubsta',        name = 'Dubsta',                        brand = 'Benefactor',      price = 500000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'fq2',           name = 'FQ2',                           brand = 'Fathom',          price = 400000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'granger',       name = 'Granger',                       brand = 'Declasse',        price = 600000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'novak',         name = 'Novak',                         brand = 'Lampadati',       price = 450000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'rebla',         name = 'Rebla GTS',                     brand = 'Übermacht',       price = 450000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'toros',         name = 'Toros',                         brand = 'Pegassi',         price = 650000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'xls',           name = 'XLS',                           brand = 'Benefactor',      price = 500000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'granger2',      name = 'Granger 3600LX',                brand = 'Declasse',        price = 600000,  category = 'suvs',           type = 'automobile', shop = 'pdm' },
    { model = 'focus2003',     name = 'Focus',                         brand = 'Ford',            price = 600000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'comet7',        name = 'Comet',                         brand = 'S2 Cabrio',       price = 500000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'felon2',        name = 'Felon GT',                      brand = 'Lampadati',       price = 470000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'jackal',        name = 'Jackal',                        brand = 'Ocelot',          price = 500000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'oracle2',       name = 'Oracle XS',                     brand = 'Übermacht',       price = 480000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'sentinel',      name = 'Sentinel',                      brand = 'Übermacht',       price = 490000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'sentinel2',     name = 'Sentinel XS',                   brand = 'Übermacht',       price = 450000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'windsor',       name = 'Windsor',                       brand = 'Enus',            price = 600000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'windsor2',      name = 'Windsor Drop',                  brand = 'Enus',            price = 650000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'zion',          name = 'Zion',                          brand = 'Übermacht',       price = 550000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'zion2',         name = 'Zion Cabrio',                   brand = 'Übermacht',       price = 560000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'previon',       name = 'Previon',                       brand = 'Karin',           price = 700000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'champion',      name = 'Champion',                      brand = 'Dewbauchee',      price = 650000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'futo',          name = 'Futo',                          brand = 'Karin',           price = 550500,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'sentinel3',     name = 'Sentinel Classic',              brand = 'Übermacht',       price = 700000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'kanjosj',       name = 'Kanjo SJ',                      brand = 'Dinka',           price = 500000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'postlude',      name = 'Postlude',                      brand = 'Dinka',           price = 900000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'tahoma',        name = 'Tahoma Coupe',                  brand = 'Declasse',        price = 500000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    { model = 'broadway',      name = 'Broadway',                      brand = 'Classique',       price = 800000,  category = 'coupes',         type = 'automobile', shop = 'pdm' },
    --- Muscle (5)
    { model = 'elegyrh7',      name = 'Elegy RH-7',                    brand = 'Annis',           price = 500000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'bigote',        name = 'bigote',                        brand = 'Honda',           price = 800000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'doblo',         name = 'Fiat Doblo',                    brand = 'doblo',           price = 600000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'dominator',     name = 'Dominator',                     brand = 'Vapid',           price = 625000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'dominator3',    name = 'Dominator GTX',                 brand = 'Vapid',           price = 700000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'dominator7',    name = 'Dominator ASP',                 brand = 'Vapid',           price = 710000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'dominator8',    name = 'Dominator GTT',                 brand = 'Vapid',           price = 800000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'dukes',         name = 'Dukes',                         brand = 'Imponte',         price = 500000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'faction',       name = 'Faction',                       brand = 'Willard',         price = 700000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'gauntlet',      name = 'Gauntlet',                      brand = 'Bravado',         price = 500000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'hermes',        name = 'Hermes',                        brand = 'Albany',          price = 535000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'lurcher',       name = 'Lurcher',                       brand = 'Bravado',         price = 650000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'slamvan',       name = 'Slam Van',                      brand = 'Vapid',           price = 500000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'stalion',       name = 'Stallion',                      brand = 'Declasse',        price = 600000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'tampa',         name = 'Tampa',                         brand = 'Declasse',        price = 450000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'tulip',         name = 'Tulip',                         brand = 'Declasse',        price = 800000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'vamos',         name = 'Vamos',                         brand = 'Declasse',        price = 600000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'vigero',        name = 'Vigero',                        brand = 'Declasse',        price = 500000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'virgo',         name = 'Virgo',                         brand = 'Albany',          price = 620000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'voodoo',        name = 'Voodoo',                        brand = 'Declasse',        price = 200000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'yosemite',      name = 'Yosemite',                      brand = 'Declasse',        price = 300000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'yosemite2',     name = 'Yosemite Drift',                brand = 'Declasse',        price = 250000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'buffalo4',      name = 'Buffalo STX',                   brand = 'Bravado',         price = 150000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'manana',        name = 'Manana',                        brand = 'Albany',          price = 200000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'manana2',       name = 'Manana Custom',                 brand = 'Albany',          price = 150000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'tampa2',        name = 'Drift Tampa',                   brand = 'Declasse',        price = 130000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'ruiner4',       name = 'Ruiner ZZ-8',                   brand = 'Imponte',         price = 120000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'vigero2',       name = 'Vigero ZX',                     brand = 'Declasse',        price = 170000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'weevil2',       name = 'Weevil Custom',                 brand = 'BF',              price = 130000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'buffalo5',      name = 'Buffalo EVX',                   brand = 'Bravado',         price = 180000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'tulip2',        name = 'Tulip M-100',                   brand = 'Declasse',        price = 150000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'clique2',       name = 'Clique Wagon',                  brand = 'Vapid',           price = 160000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'brigham',       name = 'Brigham',                       brand = 'Albany',          price = 110000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    { model = 'greenwood',     name = 'Greenwood',                     brand = 'Bravado',         price = 110000,  category = 'muscle',         type = 'automobile', shop = 'pdm' },
    --- Sports Classic
    { model = 'zrgpr',         name = 'ZR350 ',                        brand = 'Annis',           price = 300000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'fiat124',       name = 'fiat124',                       brand = 'Fiat',            price = 680000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = '2018zl1',       name = 'Chevrolet Camaro ZL1',          brand = 'Ocelot',          price = 250000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'ardent',        name = 'Ardent',                        brand = 'Ocelot',          price = 200000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'btype',         name = 'Roosevelt',                     brand = 'Albany',          price = 220000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'btype2',        name = 'Franken Stange',                brand = 'Albany',          price = 230000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'btype3',        name = 'Roosevelt Valor',               brand = 'Albany',          price = 250000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'casco',         name = 'Casco',                         brand = 'Lampadati',       price = 90000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'infernus2',     name = 'Infernus Classic',              brand = 'Pegassi',         price = 200000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'nebula',        name = 'Nebula',                        brand = 'Vulcar',          price = 15000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'rapidgt3',      name = 'Rapid GT Classic',              brand = 'Dewbauchee',      price = 90000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'retinue',       name = 'Retinue',                       brand = 'Vapid',           price = 80000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'retinue2',      name = 'Retinue MKII',                  brand = 'Vapid',           price = 80000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'savestra',      name = 'Savestra',                      brand = 'Annis',           price = 70000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'stinger',       name = 'Stinger',                       brand = 'Grotti',          price = 85000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'stingergt',     name = 'Stinger GT',                    brand = 'Grotti',          price = 90000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'swinger',       name = 'Swinger',                       brand = 'Ocelot',          price = 681000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'torero',        name = 'Torero',                        brand = 'Pegassi',         price = 120000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'tornado5',      name = 'Tornado Custom',                brand = 'Declasse',        price = 220000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'turismo2',      name = 'Turismo Classic',               brand = 'Grotti',          price = 670000,  category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'zion3',         name = 'Zion Classic',                  brand = 'Übermacht',       price = 60000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'cheburek',      name = 'Cheburek',                      brand = 'Rune',            price = 20000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    { model = 'coquette2',     name = 'Coquette Classic',              brand = 'Invetero',        price = 75000,   category = 'sportsclassics', type = 'automobile', shop = 'pdm' },
    --- Sports
    { model = 'alpha',         name = 'Alpha',                         brand = 'Albany',          price = 130000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'banshee',       name = 'Banshee',                       brand = 'Bravado',         price = 150000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'bestiagts',     name = 'Bestia GTS',                    brand = 'Grotti',          price = 170000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'buffalo',       name = 'Buffalo',                       brand = 'Bravado',         price = 80000,   category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'buffalo2',      name = 'Buffalo S',                     brand = 'Bravado',         price = 100000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'comet5',        name = 'Comet SR',                      brand = 'Pfister',         price = 200000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'coquette',      name = 'Coquette',                      brand = 'Invetero',        price = 125000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'coquette4',     name = 'Coquette D10',                  brand = 'Invetero',        price = 120000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'drafter',       name = '8F Drafter',                    brand = 'Obey',            price = 130000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'elegy',         name = 'Elegy Retro Custom',            brand = 'Annis',           price = 120000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'elegy2',        name = 'Elegy RH8',                     brand = 'Annis',           price = 130000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'flashgt',       name = 'Flash GT',                      brand = 'Vapid',           price = 200000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'furoregt',      name = 'Furore GT',                     brand = 'Lampadati',       price = 130000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'gb200',         name = 'GB 200',                        brand = 'Vapid',           price = 140000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'komoda',        name = 'Komoda',                        brand = 'Lampadati',       price = 110000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'imorgon',       name = 'Imorgon',                       brand = 'Överflöd',        price = 100000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'italigto',      name = 'Itali GTO',                     brand = 'Progen',          price = 150000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'jugular',       name = 'Jugular',                       brand = 'Ocelot',          price = 200000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'jester',        name = 'Jester',                        brand = 'Dinka',           price = 130000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'jester2',       name = 'Jester Racecar',                brand = 'Dinka',           price = 140000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'jester3',       name = 'Jester Classic',                brand = 'Dinka',           price = 150000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'khamelion',     name = 'Khamelion',                     brand = 'Hijak',           price = 160000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'kuruma',        name = 'Kuruma',                        brand = 'Karin',           price = 120000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'locust',        name = 'Locust',                        brand = 'Ocelot',          price = 180000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'lynx',          name = 'Lynx',                          brand = 'Ocelot',          price = 150000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'massacro',      name = 'Massacro',                      brand = 'Dewbauchee',      price = 110000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'massacro2',     name = 'Massacro Racecar',              brand = 'Dewbauchee',      price = 160000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'neo',           name = 'Neo',                           brand = 'Vysser',          price = 120000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'neon',          name = 'Neon',                          brand = 'Pfister',         price = 180000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'ninef',         name = '9F',                            brand = 'Obey',            price = 130000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'ninef2',        name = '9F Cabrio',                     brand = 'Obey',            price = 135000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'omnis',         name = 'Omnis',                         brand = 'Wow',             price = 220000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'paragon',       name = 'Paragon',                       brand = 'Enus',            price = 190000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'pariah',        name = 'Pariah',                        brand = 'Ocelot',          price = 210000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'penumbra',      name = 'Penumbra',                      brand = 'Maibatsu',        price = 130000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'penumbra2',     name = 'Penumbra FF',                   brand = 'Maibatsu',        price = 135000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'rapidgt',       name = 'Rapid GT',                      brand = 'Dewbauchee',      price = 100000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'rapidgt2',      name = 'Rapid GT Convertible',          brand = 'Dewbauchee',      price = 130000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'raptor',        name = 'Raptor',                        brand = 'BF',              price = 150000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'revolter',      name = 'Revolter',                      brand = 'Übermacht',       price = 170000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'ruston',        name = 'Ruston',                        brand = 'Hijak',           price = 180000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'schafter3',     name = 'Schafter V12',                  brand = 'Benefactor',      price = 130000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'schafter4',     name = 'Schafter LWB',                  brand = 'Benefactor',      price = 150000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'schlagen',      name = 'Schlagen GT',                   brand = 'Benefactor',      price = 160000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'schwarzer',     name = 'Schwartzer',                    brand = 'Benefactor',      price = 147000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'seven70',       name = 'Seven-70',                      brand = 'Dewbauchee',      price = 145000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'specter',       name = 'Specter',                       brand = 'Dewbauchee',      price = 160000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'streiter',      name = 'Streiter',                      brand = 'Benefactor',      price = 185000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'sugoi',         name = 'Sugoi',                         brand = 'Dinka',           price = 167000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'sultan',        name = 'Sultan',                        brand = 'Karin',           price = 120000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'sultan2',       name = 'Sultan Custom',                 brand = 'Karin',           price = 135000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'surano',        name = 'Surano',                        brand = 'Benefactor',      price = 180000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'tropos',        name = 'Tropos Rallye',                 brand = 'Lampadati',       price = 135000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'verlierer2',    name = 'Verlierer',                     brand = 'Bravado',         price = 145000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'vstr',          name = 'V-STR',                         brand = 'Albany',          price = 130000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'italirsx',      name = 'Itali RSX',                     brand = 'Progen',          price = 135000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'zr350',         name = 'ZR350',                         brand = 'Annis',           price = 140000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'calico',        name = 'Calico GTF',                    brand = 'Karin',           price = 220000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'futo2',         name = 'Futo GTX',                      brand = 'Karin',           price = 110000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'euros',         name = 'Euros',                         brand = 'Annis',           price = 130000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'jester4',       name = 'Jester RR',                     brand = 'Dinka',           price = 140000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'remus',         name = 'Remus',                         brand = 'Annis',           price = 135000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'comet6',        name = 'Comet S2',                      brand = 'Pfister',         price = 150000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'growler',       name = 'Growler',                       brand = 'Pfister',         price = 115000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'vectre',        name = 'Vectre',                        brand = 'Emperor',         price = 142000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'cypher',        name = 'Cypher',                        brand = 'Übermacht',       price = 145000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'sultan3',       name = 'Sultan Classic Custom',         brand = 'Karin',           price = 150000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'rt3000',        name = 'RT3000',                        brand = 'Dinka',           price = 110000,  category = 'sports',         type = 'automobile', shop = 'luxury' },                                                                
    { model = 'visione',       name = 'Visione',                       brand = 'Grotti',          price = 180000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'stingertt',     name = 'Itali GTO Stinger TT',          brand = 'Maibatsu',        price = 148000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'omnisegt',      name = 'Omnis e-GT',                    brand = 'Obey',            price = 135000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'sentinel4',     name = 'Sentinel Classic Widebody',     brand = 'Übermacht',       price = 130000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'sm722',         name = 'SM722',                         brand = 'Benefactor',      price = 120000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'tenf',          name = '10F',                           brand = 'Obey',            price = 125000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'tenf2',         name = '10F Widebody',                  brand = 'Obey',            price = 145000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'everon2',       name = 'Everon Hotring',                brand = 'Karin',           price = 150000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'issi8',         name = 'Issi Rally',                    brand = 'Weeny',           price = 130000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'corsita',       name = 'Corsita',                       brand = 'Lampadati',       price = 125000,  category = 'sports',         type = 'automobile', shop = 'luxury' },
    { model = 'gauntlet6',     name = 'Hotring Hellfire',              brand = 'Bravado',         price = 132500,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'coureur',       name = 'La Coureuse',                   brand = 'Penaud',          price = 125000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'r300',          name = '300R',                          brand = 'Annis',           price = 115000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    { model = 'panthere',      name = 'Panthere',                      brand = 'Toundra',         price = 138000,  category = 'sports',         type = 'automobile', shop = 'pdm' },
    --- Super
    { model = 'polo2018',      name = 'Polo',                          brand = 'Volkswagen',      price = 950000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'fk8',           name = 'HONDA CIVIC TYPE R',            brand = 'Honda',           price = 900000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'adder',         name = 'Adder',                         brand = 'Truffade',        price = 150000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'autarch',       name = 'Autarch',                       brand = 'Överflöd',        price = 210000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'banshee2',      name = 'Banshee 900R',                  brand = 'Bravado',         price = 115000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'bullet',        name = 'Bullet',                        brand = 'Vapid',           price = 180000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'cyclone',       name = 'Cyclone',                       brand = 'Coil',            price = 145800,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'entity2',       name = 'Entity XXR',                    brand = 'Överflöd',        price = 160000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'entityxf',      name = 'Entity XF',                     brand = 'Överflöd',        price = 186000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'fmj',           name = 'FMJ',                           brand = 'Vapid',           price = 180000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'furia',         name = 'Furia',                         brand = 'Grotti',          price = 170000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'gp1',           name = 'GP1',                           brand = 'Progen',          price = 145000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'infernus',      name = 'Infernus',                      brand = 'Pegassi',         price = 210000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'italigtb',      name = 'Itali GTB',                     brand = 'Progen',          price = 220000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'italigtb2',     name = 'Itali GTB Custom',              brand = 'Progen',          price = 245000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'krieger',       name = 'Krieger',                       brand = 'Benefactor',      price = 180000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'le7b',          name = 'RE-7B',                         brand = 'Annis',           price = 148000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'penetrator',    name = 'Penetrator',                    brand = 'Ocelot',          price = 170000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'sc1',           name = 'SC1',                           brand = 'Übermacht',       price = 145000,   category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'sheava',        name = 'ETR1',                          brand = 'Emperor',         price = 160000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 't20',           name = 'T20',                           brand = 'Progen',          price = 270000, category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'taipan',        name = 'Taipan',                        brand = 'Cheval',          price = 180000, category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'tempesta',      name = 'Tempesta',                      brand = 'Pegassi',         price = 200000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'tezeract',      name = 'Tezeract',                      brand = 'Pegassi',         price = 230000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'thrax',         name = 'Thrax',                         brand = 'Truffade',        price = 320000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'tigon',         name = 'Tigon',                         brand = 'Lampadati',       price = 230000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'turismor',      name = 'Turismo R',                     brand = 'Grotti',          price = 250000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'tyrant',        name = 'Tyrant',                        brand = 'Överflöd',        price = 380000, category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'tyrus',         name = 'Tyrus',                         brand = 'Progen',          price = 175000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'vacca',         name = 'Vacca',                         brand = 'Pegassi',         price = 180000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'vagner',        name = 'Vagner',                        brand = 'Dewbauchee',      price = 165000, category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'xa21',          name = 'XA-21',                         brand = 'Ocelot',          price = 270000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'zentorno',      name = 'Zentorno',                      brand = 'Pegassi',         price = 230000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'zorrusso',      name = 'Zorrusso',                      brand = 'Pegassi',         price = 250000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'ignus',         name = 'Ignus',                         brand = 'Pegassi',         price = 380000, category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'zeno',          name = 'Zeno',                          brand = 'Överflöd',        price = 225000, category = 'super',          type = 'automobile', shop = 'pdm' },
    { model = 'deveste',       name = 'Deveste',                       brand = 'Principe',        price = 350000,  category = 'super',          type = 'automobile', shop = 'luxury' },   
    { model = 'torero2',       name = 'Torero XO',                     brand = 'Pegassi',         price = 250000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    { model = 'entity3',       name = 'Entity MT',                     brand = 'Overflod',        price = 210000,  category = 'super',          type = 'automobile', shop = 'luxury' },
    --- Motorcycles (8)
    { model = 'akuma',         name = 'Akuma',                         brand = 'Dinka',           price = 60000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'avarus',        name = 'Avarus',                        brand = 'LCC',             price = 45000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'bagger',        name = 'Bagger',                        brand = 'WMC',             price = 55000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'bati',          name = 'Bati 801',                      brand = 'Pegassi',         price = 38000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'bati2',         name = 'Bati 801RR',                    brand = 'Pegassi',         price = 40000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'bf400',         name = 'BF400',                         brand = 'Nagasaki',        price = 50000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'carbonrs',      name = 'Carbon RS',                     brand = 'Nagasaki',        price = 70000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'chimera',       name = 'Chimera',                       brand = 'Nagasaki',        price = 80000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'cliffhanger',   name = 'Cliffhanger',                   brand = 'Western',         price = 65000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'daemon',        name = 'Daemon',                        brand = 'WMC',             price = 60000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'daemon2',       name = 'Daemon Custom',                 brand = 'Western',         price = 65000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'defiler',       name = 'Defiler',                       brand = 'Shitzu',          price = 40000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'diablous',      name = 'Diablous',                      brand = 'Principe',        price = 45000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'diablous2',     name = 'Diablous Custom',               brand = 'Principe',        price = 50000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'double',        name = 'Double-T',                      brand = 'Dinka',           price = 70000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'enduro',        name = 'Enduro',                        brand = 'Dinka',           price = 45000,    category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'esskey',        name = 'Esskey',                        brand = 'Pegassi',         price = 90000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'faggio',        name = 'Faggio Sport',                  brand = 'Pegassi',         price = 25000,    category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'fcr',           name = 'FCR 1000',                      brand = 'Pegassi',         price = 30000,    category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'fcr2',          name = 'FCR 1000 Custom',               brand = 'Pegassi',         price = 35000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'gargoyle',      name = 'Gargoyle',                      brand = 'Western',         price = 45000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'hakuchou',      name = 'Hakuchou',                      brand = 'Shitzu',          price = 70000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'hakuchou2',     name = 'Hakuchou Drag',                 brand = 'Shitzu',          price = 75000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'hexer',         name = 'Hexer',                         brand = 'LCC',             price = 60000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'innovation',    name = 'Innovation',                    brand = 'LLC',             price = 40000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'lectro',        name = 'Lectro',                        brand = 'Principe',        price = 60000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'manchez',       name = 'Manchez',                       brand = 'Maibatsu',        price = 42500,    category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'nemesis',       name = 'Nemesis',                       brand = 'Principe',        price = 41000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'nightblade',    name = 'Nightblade',                    brand = 'WMC',             price = 70000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'pcj',           name = 'PCJ-600',                       brand = 'Shitzu',          price = 50000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'ruffian',       name = 'Ruffian',                       brand = 'Pegassi',         price = 50000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'sanchez',       name = 'Sanchez Livery',                brand = 'Maibatsu',        price = 60000,    category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'sanchez2',      name = 'Sanchez',                       brand = 'Maibatsu',        price = 65000,    category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'sanctus',       name = 'Sanctus',                       brand = 'LCC',             price = 52000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'sovereign',     name = 'Sovereign',                     brand = 'WMC',             price = 40000,  category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'stryder',       name = 'Stryder',                       brand = 'Nagasaki',        price = 60000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'thrust',        name = 'Thrust',                        brand = 'Dinka',           price = 45000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'vader',         name = 'Vader',                         brand = 'Shitzu',          price = 38000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'vindicator',    name = 'Vindicator',                    brand = 'Dinka',           price = 35000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'vortex',        name = 'Vortex',                        brand = 'Pegassi',         price = 40000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'wolfsbane',     name = 'Wolfsbane',                     brand = 'Western',         price = 35000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'manchez2',      name = 'Manchez Scout',                 brand = 'Maibatsu',        price = 50000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'shinobi',       name = 'Shinobi',                       brand = 'Nagasaki',        price = 70000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'reever',        name = 'Reever',                        brand = 'Western',         price = 50000,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    { model = 'manchez3',      name = 'Manchez Scout Classic',         brand = 'Maibatsu',        price = 62200,   category = 'motorcycles',    type = 'bike',       shop = 'pdm' },
    --- Off-Road
    { model = 'amarok',         name = 'Amarok',                         brand = 'Volkswagen',           price = 140000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'bifta',         name = 'Bifta',                         brand = 'Annis',           price = 155000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'blazer',        name = 'Blazer',                        brand = 'Annis',           price = 150000,    category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'brawler',       name = 'Brawler',                       brand = 'Annis',           price = 120000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'dubsta3',       name = 'Dubsta 6x6',                    brand = 'Annis',           price = 110000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'everon',        name = 'Everon',                        brand = 'Karin',           price = 190000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'kamacho',       name = 'Kamacho',                       brand = 'Canis',           price = 150000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'mesa3',         name = 'Mesa Merryweather',             brand = 'Canis',           price = 120000,  category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'rancherxl',     name = 'Rancher XL',                    brand = 'Declasse',        price = 90000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'rebel2',        name = 'Rebel',                         brand = 'Vapid',           price = 75000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'riata',         name = 'Riata',                         brand = 'Vapid',           price = 260000,  category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'sandking',      name = 'Sandking XL',                   brand = 'Vapid',           price = 250000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'sandking2',     name = 'Sandking SWB',                  brand = 'Vapid',           price = 270000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'vagrant',       name = 'Vagrant',                       brand = 'Maxwell',         price = 250000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'verus',         name = 'Verus',                         brand = 'Dinka',           price = 200000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'winky',         name = 'Winky',                         brand = 'Vapid',           price = 120000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'yosemite3',     name = 'Yosemite Rancher',              brand = 'Declasse',        price = 125000,  category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'mesa',          name = 'Mesa',                          brand = 'Canis',           price = 120000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'ratel',         name = 'Ratel',                         brand = 'Vapid',           price = 330000,  category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'l35',           name = 'Walton L35',                    brand = 'Declasse',        price = 270000,  category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'monstrociti',   name = 'MonstroCiti',                   brand = 'Maibatsu',        price = 250000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    { model = 'draugur',       name = 'Draugur',                       brand = 'Declasse',        price = 320000,   category = 'offroad',        type = 'automobile', shop = 'pdm' },
    --- Utility
    { model = 'slamtruck',     name = 'Slam Truck',                    brand = 'Vapid',           price = 100000,  category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'caddy3',        name = 'Caddy (Bunker)',                brand = 'Nagasaki',        price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'caddy2',        name = 'Caddy (Civilian)',              brand = 'Nagasaki',        price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'caddy3',        name = 'Caddy (Golf)',                  brand = 'Nagasaki',        price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'utillitruck',   name = 'Utility Truck (Cherry Picker)', brand = 'Brute',           price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'utillitruck2',  name = 'Utility Truck (Van)',           brand = 'Brute',           price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'utillitruck3',  name = 'Utility Truck (Contender)',     brand = 'Vapid',           price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'tractor',       name = 'Tractor',                       brand = 'Stanley',         price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'tractor2',      name = 'Fieldmaster',                   brand = 'Stanley',         price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'tractor3',      name = 'Fieldmaster',                   brand = 'Stanley',         price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'towtruck',      name = 'Tow Truck (Large)',             brand = 'Vapid',           price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'towtruck2',     name = 'Tow Truck (Small)',             brand = 'Vapid',           price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'scrap',         name = 'Scrap Truck',                   brand = 'Vapid',           price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'sadler',        name = 'Sadler',                        brand = 'Vapid',           price = 20000,   category = 'utility',        type = 'automobile', shop = 'pdm' },
    { model = 'ripley',        name = 'Ripley',                        brand = 'HVY',             price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'mower',         name = 'Lawn Mower',                    brand = 'Jacksheepe',      price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'forklift',      name = 'Forklift',                      brand = 'HVY',             price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'docktug',       name = 'Docktug',                       brand = 'HVY',             price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'airtug',        name = 'Airtug',                        brand = 'HVY',             price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    --- Vans 
    { model = 'nspeedo',         name = 'Transit',                         brand = 'Ford',         price = 200000,   category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'bison',         name = 'Bison',                         brand = 'Bravado',         price = 30000,   category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'bobcatxl',      name = 'Bobcat XL Open',                brand = 'Vapid',           price = 35000,   category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'burrito3',      name = 'Burrito',                       brand = 'Declasse',        price = 40000,    category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'gburrito2',     name = 'Burrito Custom',                brand = 'Declasse',        price = 45000,   category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'rumpo',         name = 'Rumpo',                         brand = 'Bravado',         price = 100000,    category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'journey',       name = 'Journey',                       brand = 'Zirconium',       price = 100000,    category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'minivan',       name = 'Minivan',                       brand = 'Vapid',           price = 35000,    category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'minivan2',      name = 'Minivan Custom',                brand = 'Vapid',           price = 55000,   category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'paradise',      name = 'Paradise',                      brand = 'Bravado',         price = 40000,    category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'rumpo3',        name = 'Rumpo Custom',                  brand = 'Bravado',         price = 75000,   category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'speedo',        name = 'Speedo',                        brand = 'Vapid',           price = 80000,   category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'speedo4',       name = 'Speedo Custom',                 brand = 'Vapid',           price = 50000,   category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'surfer',        name = 'Surfer',                        brand = 'BF',              price = 40000,    category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'youga3',        name = 'Youga Classic 4x4',             brand = 'Bravado',         price = 550000,   category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'youga',         name = 'Youga',                         brand = 'Bravado',         price = 40000,    category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'pony',          name = 'Pony',                          brand = 'Brute',           price = 100000,   category = 'vans',           type = 'automobile', shop = 'truck' },
    { model = 'surfer3',       name = 'Surfer Custom',                 brand = 'BF',              price = 50000,   category = 'vans',           type = 'automobile', shop = 'pdm' },
    { model = 'speedo5',       name = 'Speedo Custom',                 brand = 'Vapid',           price = 40000,  category = 'vans',           type = 'automobile', shop = 'pdm' },
    --- Cycles
    { model = 'bmx',           name = 'BMX',                           brand = 'Bike',            price = 1600,     category = 'cycles',         type = 'bike',       shop = 'pdm' },
    { model = 'cruiser',       name = 'Cruiser',                       brand = 'Bike',            price = 5100,     category = 'cycles',         type = 'bike',       shop = 'pdm' },
    { model = 'fixter',        name = 'Fixter',                        brand = 'Bike',            price = 2250,     category = 'cycles',         type = 'bike',       shop = 'pdm' },
    { model = 'scorcher',      name = 'Scorcher',                      brand = 'Bike',            price = 2800,     category = 'cycles',         type = 'bike',       shop = 'pdm' },
    { model = 'tribike',       name = 'Whippet Race Bike',             brand = 'Bike',            price = 28000,     category = 'cycles',         type = 'bike',       shop = 'pdm' },
    { model = 'tribike2',      name = 'Endurex Race Bike',             brand = 'Bike',            price = 30000,     category = 'cycles',         type = 'bike',       shop = 'pdm' },
    { model = 'tribike3',      name = 'Tri-Cycles Race Bike',          brand = 'Bike',            price = 32000,     category = 'cycles',         type = 'bike',       shop = 'pdm' },
    { model = 'inductor',      name = 'Inductor',                      brand = 'Coil',            price = 50000,    category = 'cycles',         type = 'bike',       shop = 'pdm' },
    { model = 'inductor2',     name = 'Junk Energy Inductor',          brand = 'Coil',            price = 50000,    category = 'cycles',         type = 'bike',       shop = 'pdm' },
    --- Boats
    { model = 'dinghy4',       name = 'Weaponized Dinghy',             brand = 'Nagasaki',        price = 4,   category = 'boats',          type = 'boat',       shop = 'none' },
    { model = 'avisa',         name = 'Avisa',                         brand = 'Kraken Subs',     price = 40000,   category = 'boats',          type = 'boat',       shop = 'none' },
    { model = 'patrolboat',    name = 'Kurtz 31 Patrol Boat',          brand = 'Unknown',         price = 40000,   category = 'boats',          type = 'boat',       shop = 'none' },
    { model = 'longfin',       name = 'Longfin',                       brand = 'Shitzu',          price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'tug',           name = 'Tug',                           brand = 'Buckingham',      price = 40000,   category = 'boats',          type = 'boat',       shop = 'none' },
    { model = 'toro',          name = 'Toro',                          brand = 'Lampadati',       price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'toro2',         name = 'Toro Yacht',                    brand = 'Lampadati',       price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'submersible2',  name = 'Kraken',                        brand = 'Kraken Subs',     price = 40000,   category = 'boats',          type = 'boat',       shop = 'none' },
    { model = 'speeder',       name = 'Speeder',                       brand = 'Pegassi',         price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'speeder2',      name = 'Speeder Yacht',                 brand = 'Pegassi',         price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'tropic',        name = 'Tropic',                        brand = 'Shitzu',          price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'tropic2',       name = 'Tropic Yacht',                  brand = 'Shitzu',          price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'suntrap',       name = 'Suntrap',                       brand = 'Shitzu',          price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'submersible',   name = 'Submersible',                   brand = 'Kraken Subs',     price = 40000,   category = 'boats',          type = 'boat',       shop = 'none' },
    { model = 'squalo',        name = 'Squalo',                        brand = 'Shitzu',          price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'seashark',      name = 'Seashark',                      brand = 'Speedophile',     price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'seashark3',     name = 'Seashark Yacht',                brand = 'Speedophile',     price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'marquis',       name = 'Marquis',                       brand = 'Dinka',           price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'jetmax',        name = 'Jetmax',                        brand = 'Shitzu',          price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'dinghy',        name = 'Dinghy 2-Seater',               brand = 'Nagasaki',        price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'dinghy2',       name = 'Dinghy 4-Seater',               brand = 'Nagasaki',        price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'dinghy3',       name = 'Dinghy (Heist)',                brand = 'Nagasaki',        price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'dinghy4',       name = 'Dinghy Yacht',                  brand = 'Nagasaki',        price = 40000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    --- Service
    { model = 'brickade',      name = 'Brickade',                      brand = 'MTL',             price = 99999999999999,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'brickade2',     name = 'Brickade 6x6',                  brand = 'MTL',             price = 99999999999999,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'pbus2',         name = 'Festival Bus',                  brand = 'Unknown',         price = 99999999999999,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'wastelander',   name = 'Wastelander',                   brand = 'MTL',             price = 99999999999999,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'metrotrain',    name = 'Metro Train',                   brand = 'Unknown',         price = 99999999999999,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'freight',       name = 'Freight Train',                 brand = 'Unknown',         price = 99999999999999,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'cablecar',      name = 'Cable Car',                     brand = 'Unknown',         price = 99999999999999,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'trash',         name = 'Trashmaster',                   brand = 'JoBuilt',         price = 99999999999999,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'trash2',        name = 'Trashmaster',                   brand = 'JoBuilt',         price = 99999999999999,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'tourbus',       name = 'Tour Bus',                      brand = 'Brute',           price = 99999999999999,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'taxi',          name = 'Taxi',                          brand = 'Vapid',           price = 99999999999999,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'rentalbus',     name = 'Rental Shuttle Bus',            brand = 'Brute',           price = 99999999999999,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'coach',         name = 'Dashound',                      brand = 'Brute',           price = 99999999999999,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'bus',           name = 'Bus',                           brand = 'Brute',           price = 99999999999999,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'airbus',        name = 'Airport Bus',                   brand = 'Brute',           price = 99999999999999,  category = 'service',        type = 'automobile', shop = 'none' },
    --- Emergency
    { model = 'riot',          name = 'Police Riot',                   brand = 'Brute',           price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'riot2',         name = 'RCV',                           brand = 'Unknown',         price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'pbus',          name = 'Police Prison Bus',             brand = 'Vapid',           price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'police',        name = 'Police Cruiser',                brand = 'Vapid',           price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'police2',       name = 'Police Buffalo',                brand = 'Vapid',           price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'police3',       name = 'Police Interceptor',            brand = 'Vapid',           price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'police4',       name = 'Unmarked Cruiser',              brand = 'Vapid',           price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'sheriff',       name = 'Sheriff SUV',                   brand = 'Declasse',        price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'sheriff2',      name = 'Sheriff Cruiser',               brand = 'Vapid',           price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'policeold1',    name = 'Police Rancher',                brand = 'Declasse',        price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'policeold2',    name = 'Police Roadcruiser',            brand = 'Albany',          price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'policet',       name = 'Police Transporter',            brand = 'Vapid',           price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'policeb',       name = 'Police Bike',                   brand = 'Vapid',           price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'polmav',        name = 'Police Maverick',               brand = 'Buckingham',      price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'ambulance',     name = 'Ambulance',                     brand = 'Brute',           price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'firetruk',      name = 'Fire Truck',                    brand = 'MTL',             price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'lguard',        name = 'Lifeguard',                     brand = 'Declasse',        price = 99999999999999,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'seashark2',     name = 'Seashark Lifeguard',            brand = 'Speedophile',     price = 99999999999999,   category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'pranger',       name = 'Park Ranger',                   brand = 'Declasse',        price = 99999999999999,   category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'fbi',           name = 'FIB Buffalo',                   brand = 'Bravado',         price = 99999999999999,   category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'fbi2',          name = 'FIB Granger',                   brand = 'Declasse',        price = 99999999999999,   category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'predator',      name = 'Police Predator',               brand = 'Unknown',         price = 99999999999999,   category = 'emergency',      type = 'automobile', shop = 'none' },
    --- Commercial
    { model = 'cerberus',      name = 'Apocalypse Cerberus',           brand = 'MTL',             price = 99999999999999,  category = 'commercial',     type = 'automobile', shop = 'none' },
    { model = 'pounder2',      name = 'Pounder Custom',                brand = 'MTL',             price = 99999999999999,   category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'mule4',         name = 'Mule Custom',                   brand = 'Maibatsu',        price = 99999999999999,   category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'phantom3',      name = 'Phantom Custom',                brand = 'Jobuilt',         price = 99999999999999,  category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'hauler2',       name = 'Hauler Custom',                 brand = 'Jobuilt',         price = 99999999999999,  category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'phantom2',      name = 'Phantom Wedge',                 brand = 'Jobuilt',         price = 99999999999999,  category = 'commercial',     type = 'automobile', shop = 'none' },
    { model = 'mule5',         name = 'Mule (Heist)',                  brand = 'Maibatsu',        price = 99999999999999,   category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'stockade',      name = 'Stockade',                      brand = 'Brute',           price = 99999999999999,  category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'pounder',       name = 'Pounder',                       brand = 'MTL',             price = 99999999999999,   category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'phantom',       name = 'Phantom',                       brand = 'Jobuilt',         price = 99999999999999,  category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'packer',        name = 'Packer',                        brand = 'MTL',             price = 99999999999999,  category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'mule',          name = 'Mule',                          brand = 'Maibatsu',        price = 200000000,   category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'hauler',        name = 'Hauler',                        brand = 'Jobuilt',         price = 99999999999999,  category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'biff',          name = 'Biff',                          brand = 'Brute',           price = 99999999999999,  category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'benson',        name = 'Benson',                        brand = 'Vapid',           price = 99999999999999,   category = 'commercial',     type = 'automobile', shop = 'truck' },
    --- Open Wheel
    { model = 'openwheel2',    name = 'DR1',                           brand = 'Declasse',        price = 99999999999999,  category = 'openwheel',      type = 'automobile', shop = 'none' },
    { model = 'openwheel1',    name = 'BR8',                           brand = 'Benefactor',      price = 99999999999999,  category = 'openwheel',      type = 'automobile', shop = 'none' },
    { model = 'formula2',      name = 'R88',                           brand = 'Ocelot',          price = 99999999999999,  category = 'openwheel',      type = 'automobile', shop = 'none' },
    { model = 'formula',       name = 'PR4',                           brand = 'Progen',          price = 99999999999999,  category = 'openwheel',      type = 'automobile', shop = 'none' },
}

-- for i = 1, #VehiclesData do
--     Vehicles[VehiclesData[i].model] = {
--         spawncode = VehiclesData[i].model,
--         name = VehiclesData[i].name,
--         brand = VehiclesData[i].brand,
--         model = VehiclesData[i].model,
--         price = VehiclesData[i].price,
--         category = VehiclesData[i].category,
--         hash = joaat(VehiclesData[i].model),
--         type = VehiclesData[i].type,
--         shop = VehiclesData[i].shop
--     }
-- end

for k, v in pairs(VehiclesData) do
    table.insert(Vehicles, {
        spawncode = v.model,
        name = v.name,
        brand = v.brand,
        model = v.model,
        price = v.price,
        category = v.category,
        categoryLabel = Lang:t("categories." .. v.category),
        hash = joaat(v.model),
        type = v.type,
        shop = v.shop
    })
    Vehicles2[v.model] = {
        spawncode = v.model,
        name = v.name,
        brand = v.brand,
        model = v.model,
        price = v.price,
        category = v.category,
        categoryLabel = Lang:t("categories." .. v.category),
        hash = joaat(v.model),
        type = v.type,
        shop = v.shop
    }
    if not Categories[v.category] then
        Categories[v.category] = {
            name = v.category
        }
    end
end